# Service to immediately stop the drone in an emergency

# Request
# A brief HUMAN READABLE reason for the emergency stop for logging purposes
string reason
---
# Response
bool acknowledged # so this confirms that the emergency stop command has been received and is being executed
string message   # ex... "Emergency stop acknowledged, Reason: Proximity breach"
